version: '2'
services:
  cadvisor:
    labels:
      - "io.rancher.scheduler.global=true"
    tty: true
    image: google/cadvisor:v0.30.2
    stdin_open: true
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"

  node-exporter:
    labels:
      - "io.rancher.scheduler.global=true"
    tty: true
    image: prom/node-exporter:v0.15.2
    stdin_open: true

  prom-conf:
    tty: true
    image: infinityworks/prom-conf:20
    volumes:
      - /etc/prom-conf/

  prometheus:
    tty: true
    image: prom/prometheus:v2.1.0
    command: --config.file=/etc/prom-conf/prometheus.yml --storage.tsdb.path=/prometheus --web.console.libraries=/etc/prometheus/console_libraries --web.console.templates=/etc/prometheus/consoles
    labels:
      - "io.rancher.sidekicks=prom-conf"
    volumes_from:
      - prom-conf
    volumes:
      - /prometheus

  graf-db:
    tty: true
    image: infinityworks/graf-db:11
    command: cat
    volumes:
      - /var/lib/grafana/

  grafana:
    tty: true
    image: grafana/grafana:5.0.0
    labels:
      - "io.rancher.sidekicks=graf-db"
      - "traefik.enable=true"
      - "traefik.port=3000"
      - "traefik.frontend.rule=Host:grafana.mysite.com"
    environment:
      - "GF_SMTP_ENABLED=true"
      - "GF_SMTP_HOST=your.smtp.com:25"
      - "GF_SMTP_USER=your_smtp_username"
      - "GF_SMTP_PASSWORD=your_smtp_password"
      - "GF_SMTP_FROM_ADDRESS=no-reply@your.site.com"
      - "GF_SMTP_FROM_NAME=Your sender name"
    volumes_from:
       - graf-db
